FROM node:6.12.0-alpine

# Set a working directory
WORKDIR /usr/src/app

# Copy application files
COPY identifi-angular identifi-angular
COPY wait-for .

RUN apk add --no-cache make g++ python libsodium-dev && npm install -g node-gyp

WORKDIR /usr/src/app/identifi-angular
RUN yarn install --force

RUN yarn global add bower
RUN yarn global add gulp-cli

USER node
RUN bower install
CMD [ "gulp", "serve" ]
