FROM node:6.12.0-alpine

# Set a working directory
WORKDIR /usr/src/app

# Copy application files
COPY identifi-angular identifi-angular
COPY wait-for wait-for

RUN apk add --no-cache make g++ git python

WORKDIR /usr/src/app/identifi-angular
RUN yarn install --force

RUN yarn add gulp
RUN yarn global add bower
RUN yarn global add gulp-cli

RUN chown node:node .
USER node
ENV GIT_DIR=/usr/src/app/identifi-angular
RUN bower install
CMD [ "gulp", "serve" ]
