FROM node:6.12.0-alpine

# Set a working directory
WORKDIR /usr/src/app

# Copy application files
COPY identifi-angular .
COPY wait-for .

RUN yarn global add gulp-cli

USER node
CMD [ "gulp", "serve" ]
